LOAD DATA INFILE "data/userdata.dat" INTO TABLE `USER`
FIELDS TERMINATED BY "," ENCLOSED BY '"'
LINES TERMINATED BY "\r\n";

LOAD DATA INFILE "data/buyerdata.dat" INTO TABLE BUYER
FIELDS TERMINATED BY "," ENCLOSED BY '"'
LINES TERMINATED BY "\r\n";

LOAD DATA INFILE "data/sellerdata.dat" INTO TABLE SELLER
FIELDS TERMINATED BY "," ENCLOSED BY '"'
LINES TERMINATED BY "\r\n";

LOAD DATA INFILE "data/venuedata.dat" INTO TABLE VENUE
FIELDS TERMINATED BY "," ENCLOSED BY '"'
LINES TERMINATED BY "\r\n";

